name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            compiler: msvc
            c_compiler: cl
            cpp_compiler: cl
    steps:
    - uses: actions/checkout@v4

    - name: Configure and build all components
      run: |
        cmake -B formatter_lib/build -S formatter_lib
        cmake --build formatter_lib/build --config Release

        cmake -B formatter_ex_lib/build -S formatter_ex_lib -DCMAKE_PREFIX_PATH=../formatter_lib/build
        cmake --build formatter_ex_lib/build --config Release

        cmake -B solver_lib/build -S solver_lib
        cmake --build solver_lib/build --config Release

        cmake -B hello_world_application/build -S hello_world_application
        cmake --build hello_world_application/build --config Release

        cmake -B solver_application/build -S solver_application
        cmake --build solver_application/build --config Release

